using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries; // Added for Point
using System.Text.Json.Serialization; // Added for JsonIgnore

namespace SmartRouting.Models
{
    public class Address
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Ensure Id is not auto-generated by the database
        public int Id { get; set; }

        [StringLength(255)]
        public string? Name { get; set; } // Made nullable to match potential database schema and avoid warnings

        [StringLength(20)]
        public string? Phone { get; set; } // Made nullable

        [StringLength(100)]
        public string? District { get; set; } // Made nullable

        [StringLength(100)]
        public string? Province { get; set; } // Made nullable

        [StringLength(100)]
        public string? Ward { get; set; } // Made nullable

        [StringLength(255)]
        public string? Street { get; set; } // Made nullable

        [StringLength(500)]
        public string? Address1 { get; set; } // Combined address line, made nullable

        [JsonIgnore] // To prevent issues with serialization if not handled by a custom converter.
                     // We'll derive it from Lat/Lon in the DTO/controller for now.
        public Point? Location { get; set; } // Added for GEOGRAPHY type
    }
}